"""sync account schema

Revision ID: a0a850f4eae9
Revises: ff30a4f4b787
Create Date: 2025-08-31 01:16:30.993196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a850f4eae9'
down_revision: Union[str, Sequence[str], None] = 'ff30a4f4b787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('interest_rate', sa.Float(), nullable=False))
    op.add_column('accounts', sa.Column('last_interest_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'last_interest_date')
    op.drop_column('accounts', 'interest_rate')
    # ### end Alembic commands ###
